version: '3.3'
services:
    postgresql:
        image: postgres
        container_name: pg-docker
        ports:
            - "5400:5432"
        environment:
            - POSTGRES_USER=liberi
            - POSTGRES_PASSWORD=liberi
        volumes:
            - postgres_rfid:/var/lib/postgress
        restart: always
# Names our volume
volumes:
  postgres_rfid: